### ISSUE TITLE
Role can not be used from a molecule driver

### ISSUE THREAD

**Issue by fletort** [fletort/rpi-noobs-recovery#3]
Because of bug https://github.com/ansible-community/molecule/issues/2992, this role can not be used from a molecule driver. If used from a create step of a molecule test, task with `notest` tag will not be executed.

We need to use another tag to skip the no testable task.
This specific tag could be define with `skip-tags` `provisioner` option. This option seems to be used only on converge step.
 ```yaml
provisioner:
  name: ansible
  options:
    skip-tags: molecule-converge-notest
```
